CREATE TABLE "hospital_ht1" (
	"id_hospital" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tx_nombre" TEXT NOT NULL,
	PRIMARY KEY("id_hospital")
);
CREATE INDEX "hospital_ht1_index_0"
ON "hospital_ht1" ("id_hospital");

CREATE TABLE "area_ht2" (
	"id_area" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tx_nombre" TEXT NOT NULL,
	PRIMARY KEY("id_area")
);
CREATE INDEX "area_ht2_index_0"
ON "area_ht2" ("fk_id_hospital");

CREATE TABLE "areas_hospital_hp1" (
	"fk_id_hospiital" INTEGER UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fk_id_area" INTEGER
);

CREATE TABLE "sala_ht3" (
	"id_sala" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tx_nombre" TEXT NOT NULL,
	PRIMARY KEY("id_sala")
);

CREATE TABLE "habitacion_ht4" (
	"id_habitacion" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tx_habitacion" TEXT NOT NULL,
	PRIMARY KEY("id_habitacion")
);

CREATE TABLE "quirofano_ht5" (
	"id_quirofano" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tx_nombre" TEXT NOT NULL,
	PRIMARY KEY("id_quirofano")
);

CREATE TABLE "sala_area_hp2" (
	"fk_id_area" INTEGER UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fk_id_sala" INTEGER
);

CREATE TABLE "area_habitacion_hp3" (
	"fk_id_area" INTEGER UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fk_id_habitacion" INTEGER
);

CREATE TABLE "area_quirofano_hp4" (
	"fk_id_area" INTEGER UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fk_id_quirofano" INTEGER
);

ALTER TABLE "areas_hospital_hp1"
ADD FOREIGN KEY("fk_id_hospiital") REFERENCES "hospital_ht1"("id_hospital")
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "areas_hospital_hp1"
ADD FOREIGN KEY("fk_id_area") REFERENCES "area_ht2"("id_area")
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "sala_area_hp2"
ADD FOREIGN KEY("fk_id_area") REFERENCES "area_ht2"("id_area")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "sala_area_hp2"
ADD FOREIGN KEY("fk_id_sala") REFERENCES "sala_ht3"("id_sala")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "area_habitacion_hp3"
ADD FOREIGN KEY("fk_id_area") REFERENCES "area_ht2"("id_area")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "area_habitacion_hp3"
ADD FOREIGN KEY("fk_id_habitacion") REFERENCES "habitacion_ht4"("id_habitacion")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "area_quirofano_hp4"
ADD FOREIGN KEY("fk_id_area") REFERENCES "area_ht2"("id_area")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "area_quirofano_hp4"
ADD FOREIGN KEY("fk_id_quirofano") REFERENCES "quirofano_ht5"("id_quirofano")
ON UPDATE NO ACTION ON DELETE NO ACTION;