CREATE TABLE "hospital_ht1" (
	"id_hospital" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tx_nombre" TEXT NOT NULL,
	PRIMARY KEY("id_hospital")
);
CREATE INDEX "hospital_ht1_index_0"
ON "hospital_ht1" ("id_hospital");

CREATE TABLE "area_ht2" (
	"id_area" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tx_nombre" TEXT NOT NULL,
	PRIMARY KEY("id_area")
);
CREATE INDEX "area_ht2_index_0"
ON "area_ht2" ("fk_id_hospital");

CREATE TABLE "sala_ht3" (
	"id_sala" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tx_nombre" TEXT NOT NULL,
	PRIMARY KEY("id_sala")
);

CREATE TABLE "habitacion_ht4" (
	"id_habitacion" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tx_habitacion" TEXT NOT NULL,
	PRIMARY KEY("id_habitacion")
);

CREATE TABLE "quirofano_ht5" (
	"id_quirofano" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tx_nombre" TEXT NOT NULL,
	PRIMARY KEY("id_quirofano")
);

CREATE TABLE "sala_area_hp2" (
	"id_area_sala" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fk_id_area" INTEGER NOT NULL,
	"fk_id_sala" INTEGER NOT NULL,
	PRIMARY KEY("id_area_sala")
);

CREATE TABLE "area_habitacion_hp3" (
	"id_area_habitacion" INTEGER NOT NULL,
	"fk_id_habitacion" INTEGER NOT NULL,
	"fk_id_area" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	PRIMARY KEY("id_area_habitacion")
);

CREATE TABLE "area_quirofano_hp4" (
	"id_area_quirofano" INTEGER NOT NULL,
	"fk_id_quirofano" INTEGER NOT NULL,
	"fk_id_area" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	PRIMARY KEY("id_area_quirofano")
);

CREATE TABLE "hospital_area_tp1" (
	"id_hospital_area" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fk_id_hospital" INTEGER NOT NULL,
	"fk_id_area" INTEGER NOT NULL,
	PRIMARY KEY("id_hospital_area")
);

ALTER TABLE "sala_area_hp2"
ADD FOREIGN KEY("id_area_sala") REFERENCES "area_ht2"("id_area")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "sala_area_hp2"
ADD FOREIGN KEY("fk_id_area") REFERENCES "sala_ht3"("id_sala")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "area_habitacion_hp3"
ADD FOREIGN KEY("fk_id_area") REFERENCES "area_ht2"("id_area")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "area_habitacion_hp3"
ADD FOREIGN KEY("fk_id_habitacion") REFERENCES "habitacion_ht4"("id_habitacion")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "area_quirofano_hp4"
ADD FOREIGN KEY("fk_id_area") REFERENCES "area_ht2"("id_area")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "area_quirofano_hp4"
ADD FOREIGN KEY("fk_id_quirofano") REFERENCES "quirofano_ht5"("id_quirofano")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "hospital_area_tp1"
ADD FOREIGN KEY("fk_id_hospital") REFERENCES "hospital_ht1"("id_hospital")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "hospital_area_tp1"
ADD FOREIGN KEY("fk_id_area") REFERENCES "area_ht2"("id_area")
ON UPDATE NO ACTION ON DELETE NO ACTION;